apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}
  namespace: devops

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
